const express = require("express");
const fs = require("fs");
const path = require("path");

const router = express.Router();
const pdfService = require("../services/pdfService");
const {
  validateInvoicePayload,
  normalizeInvoicePayload,
} = require("../utils/validate");

const testPagePath = path.join(__dirname, "..", "views", "test-page.html");

function parseItemsField(items) {
  if (typeof items !== "string") return items;

  return items
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line) => {
      const parts = line.split(",").map((part) => part.trim());
      return {
        name: parts[0] || "",
        qty: Number(parts[1] || 1),
        price: Number(parts[2] || 0),
      };
    });
}

function prepareBody(body) {
  const payload = Object.assign({}, body || {});
  if (typeof payload.items === "string") {
    payload.items = parseItemsField(payload.items);
  }
  return payload;
}

router.get("/generate-pdf", (req, res) => {
  res.type("html").send(fs.readFileSync(testPagePath, "utf8"));
});

router.post("/generate-pdf", async (req, res) => {
  try {
    const payload = prepareBody(req.body);
    const validation = validateInvoicePayload(payload);

    if (!validation.valid) {
      return res.status(400).json({
        error: "Invalid request payload",
        details: validation.errors,
      });
    }

    const invoice = normalizeInvoicePayload(payload);
    const filename = invoice.invoiceNumber
      ? `invoice-${invoice.invoiceNumber}.pdf`
      : "invoice.pdf";

    await pdfService.generatePdf(invoice, res, filename);
  } catch (error) {
    console.error("PDF generation failed:", error);
    if (!res.headersSent) {
      res.status(500).json({ error: "Failed to generate PDF" });
    }
  }
});

router.get("/pdf/invoice", async (req, res) => {
  const sample = normalizeInvoicePayload({
    customerName: "Sample Customer",
    invoiceNumber: "DEMO-001",
    date: new Date().toISOString().slice(0, 10),
    items: [
      { name: "Service A", qty: 1, price: 100 },
      { name: "Service B", qty: 2, price: 50 },
    ],
    total: 200,
    notes: "Sample invoice generated by GET /pdf/invoice",
  });

  try {
    await pdfService.generatePdf(sample, res, "sample-invoice.pdf");
  } catch (error) {
    console.error("Sample PDF generation failed:", error);
    res.status(500).json({ error: "Failed to generate sample PDF" });
  }
});

module.exports = router;

// ---- Additional HTML renderer compatibility endpoints ----
// Provide a simple GET tester and a POST that delegates to the same PDF service
// so `/generate-pdf-html` is available even when an HTML->PDF engine isn't installed.
router.get('/generate-pdf-html', (req, res) => {
  // reuse the main UI for testing
  res.redirect('/generate-pdf');
});

router.post('/generate-pdf-html', async (req, res) => {
  try {
    const payload = prepareBody(req.body);
    const validation = validateInvoicePayload(payload);

    if (!validation.valid) {
      return res.status(400).json({ error: 'Invalid request payload', details: validation.errors });
    }

    const invoice = normalizeInvoicePayload(payload);
    const filename = invoice.invoiceNumber ? `invoice-${invoice.invoiceNumber}.pdf` : 'invoice.pdf';

    // Currently falls back to pdfService which uses pdfmake. If you install an
    // HTML->PDF renderer later we can detect and route to it here.
    await pdfService.generatePdf(invoice, res, filename);
  } catch (error) {
    console.error('HTML PDF generation failed:', error);
    if (!res.headersSent) res.status(500).json({ error: 'Failed to generate PDF' });
  }
});
